package sense

import "fmt"

// PromptEnglish builds an English-word sense-image prompt (same sticker style as literacy).
func PromptEnglish(word string) string {
	subject := englishSubject(word)
	p := fmt.Sprintf(
		"Create a clean, child-friendly cartoon illustration of %s. %s",
		subject,
		styleSuffix,
	)
	if ContainsHan(p) {
		return fmt.Sprintf(
			"Create a clean, child-friendly cartoon illustration of a single everyday object for vocabulary word %q. %s",
			word,
			styleSuffix,
		)
	}
	return p
}

func englishSubject(word string) string {
	if s, ok := englishSubjects[word]; ok {
		return s
	}
	return fmt.Sprintf("a single simple child-friendly cartoon object that clearly shows the meaning of the English word %q, with no writing on it", word)
}

var englishSubjects = map[string]string{
	"afternoon": "afternoon sun and a tree with long shadow",
	"angry": "an angry cartoon face",
	"apple": "a shiny red apple with a green leaf",
	"arm": "a cartoon arm",
	"arrow": "a simple arrow pointing right",
	"aunt": "a friendly cartoon aunt",
	"baby": "a cute cartoon baby",
	"bag": "a school backpack",
	"ball": "a colorful play ball",
	"balloon": "a single round balloon with a string",
	"banana": "a yellow banana",
	"beach": "a sandy beach with waves",
	"bear": "a cute brown cartoon bear",
	"berry": "a handful of mixed berries",
	"bike": "a bicycle",
	"bird": "a small colorful cartoon bird",
	"black": "a solid black cat silhouette that is still cute and cartoon",
	"block": "colorful building blocks stacked",
	"blue": "a bright blue balloon",
	"boat": "a small boat on water",
	"book": "an open picture book",
	"brave": "a brave cartoon child with a cape",
	"bread": "a loaf of bread",
	"brother": "a friendly cartoon boy as a brother",
	"brown": "a brown teddy bear",
	"bus": "a yellow school bus",
	"cake": "a slice of birthday cake",
	"candy": "a wrapped colorful candy",
	"car": "a simple toy car",
	"cat": "a cute cartoon cat sitting",
	"chair": "a simple chair",
	"chef": "a cartoon chef with a tall hat",
	"cherry": "two red cherries with stems",
	"cinema": "a movie theater facade",
	"circle": "a perfect circle shape",
	"class": "a small classroom with desks",
	"cloud": "a soft white cloud",
	"cloudy": "soft gray cartoon clouds",
	"coat": "a winter coat",
	"cold": "an ice cube and a scarf",
	"cool": "a gentle breeze and light jacket",
	"cousin": "a friendly cartoon child cousin",
	"cross": "a simple plus-shaped cross",
	"dad": "a friendly cartoon father waving",
	"dancer": "a cartoon dancer",
	"desk": "a simple school desk",
	"diamond": "a diamond rhombus shape",
	"doctor": "a friendly cartoon doctor",
	"dog": "a friendly cartoon dog",
	"doll": "a cute toy doll",
	"dress": "a simple dress",
	"drink": "a cartoon child drinking from a cup",
	"driver": "a cartoon bus driver",
	"ear": "a single human ear",
	"eat": "a cartoon child eating an apple",
	"egg": "a single white egg",
	"eight": "exactly eight identical blue balloons in two neat rows of four",
	"evening": "a sunset sky",
	"eye": "one large friendly cartoon eye",
	"farm": "a farm barn and field",
	"farmer": "a cartoon farmer with a straw hat",
	"firefighter": "a cartoon firefighter",
	"fish": "a single orange cartoon fish",
	"five": "exactly five identical blue balloons in a neat row",
	"flower": "a bright flower",
	"foot": "a single bare foot from the side",
	"four": "exactly four identical yellow stars in a neat row",
	"funny": "a laughing cartoon face",
	"glove": "a single glove",
	"grandma": "a friendly cartoon grandmother",
	"grandpa": "a friendly cartoon grandfather",
	"grape": "a bunch of purple grapes",
	"grass": "a patch of green grass",
	"green": "a bright green leaf",
	"hair": "a cartoon hairstyle on a head outline",
	"hand": "an open hand with palm facing forward",
	"happy": "a smiling happy cartoon face",
	"hat": "a simple hat",
	"head": "a simple cartoon head face only",
	"heart": "a red heart shape",
	"helicopter": "a helicopter",
	"home": "a cozy house",
	"hospital": "a hospital building with a medical cross symbol",
	"hot": "a thermometer with high red temperature and sun",
	"hungry": "a cartoon child looking at food hungrily",
	"juice": "a glass of orange juice",
	"jump": "a cartoon child jumping",
	"kite": "a flying diamond kite with a tail",
	"kiwi": "a kiwi fruit cut open showing green inside",
	"leg": "a cartoon leg",
	"lemon": "a bright yellow lemon",
	"library": "a library building with books",
	"lion": "a friendly cartoon lion with a mane",
	"mango": "a yellow mango fruit",
	"melon": "a green watermelon slice",
	"milk": "a glass of white milk",
	"mom": "a friendly cartoon mother waving",
	"monkey": "a playful cartoon monkey",
	"moon": "a yellow crescent moon",
	"morning": "a sunrise over a house",
	"mountain": "green mountains",
	"mouth": "an open smiling mouth",
	"museum": "a museum building",
	"night": "a night sky with a crescent moon",
	"nine": "exactly nine identical red apples in a neat three-by-three grid",
	"noon": "a bright sun high in the sky",
	"nose": "a simple cartoon nose",
	"nurse": "a friendly cartoon nurse",
	"one": "exactly one large red apple",
	"orange": "a bright orange fruit",
	"oval": "a perfect oval shape",
	"panda": "a cute cartoon panda sitting",
	"pants": "a pair of pants",
	"park": "a park with a tree and bench",
	"peach": "a fuzzy pink peach",
	"pear": "a green pear",
	"pen": "a simple writing pen",
	"pencil": "a yellow pencil",
	"pilot": "a cartoon airplane pilot",
	"pink": "a bright pink flower",
	"plane": "an airplane in the sky",
	"police": "a friendly cartoon police officer",
	"purple": "a purple cartoon grape cluster",
	"puzzle": "a jigsaw puzzle piece",
	"rabbit": "a cute white cartoon rabbit",
	"rain": "raindrops falling from a cloud",
	"rainy": "rain falling from a small gray cloud",
	"read": "a cartoon child reading a book",
	"rectangle": "a perfect rectangle shape",
	"red": "a bright red apple",
	"rice": "a bowl of cooked white rice",
	"river": "a blue river",
	"robot": "a friendly toy robot",
	"run": "a cartoon child running",
	"sad": "a sad crying cartoon face",
	"scared": "a scared cartoon face",
	"scarf": "a knitted scarf",
	"school": "a simple school building",
	"seven": "exactly seven identical yellow stars arranged neatly",
	"ship": "a large ship on the ocean",
	"shirt": "a simple shirt",
	"shoe": "a single shoe",
	"shop": "a small shop storefront",
	"singer": "a cartoon singer with a microphone",
	"sister": "a friendly cartoon girl as a sister",
	"sit": "a cartoon child sitting on a chair",
	"six": "exactly six identical green leaves in two neat rows of three",
	"skirt": "a simple skirt",
	"sleep": "a cartoon child sleeping in bed",
	"slide": "a playground slide",
	"snowy": "falling snowflakes and a small snowman",
	"sock": "a colorful sock",
	"soup": "a bowl of warm soup",
	"square": "a perfect square shape",
	"stand": "a cartoon child standing",
	"star": "a yellow five-pointed star",
	"storm": "a storm cloud with rain and a lightning bolt",
	"student": "a friendly cartoon student with a book",
	"subway": "a subway train",
	"sun": "a bright yellow sun with rays",
	"sunny": "a bright yellow sun with simple rays",
	"taxi": "a yellow taxi car",
	"teacher": "a friendly cartoon teacher",
	"ten": "exactly ten identical green leaves in two neat rows of five",
	"thirsty": "a cartoon child drinking water",
	"three": "exactly three identical red apples in a neat row",
	"tiger": "a friendly cartoon tiger",
	"tired": "a yawning tired cartoon face",
	"train": "a colorful toy train",
	"tree": "a simple green tree with a brown trunk",
	"triangle": "a perfect triangle shape",
	"truck": "a delivery truck",
	"two": "exactly two identical red apples side by side",
	"uncle": "a friendly cartoon uncle",
	"walk": "a cartoon child walking",
	"warm": "a cozy sun and soft sweater",
	"welcome": "a friendly cartoon person waving welcome",
	"white": "a white cartoon cloud",
	"windy": "a tree bent by wind with motion lines",
	"write": "a cartoon child writing with a pencil",
	"yellow": "a bright yellow sun",
	"zoo": "a zoo gate with animal silhouettes",
}
