FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1     UV_LINK_MODE=copy

WORKDIR /app

RUN python -m pip install --no-cache-dir uv -i https://pypi.tuna.tsinghua.edu.cn/simple

COPY pyproject.toml uv.lock README.md ./
COPY src ./src
RUN uv sync --frozen --no-dev
