-- Create a deduplicated single-word table derived from public.word.
-- Keeps only: id, word, meaning, difficulty, frequency, sentence.
-- Excludes phrases where word contains whitespace.
-- When a word appears in multiple PEP textbook levels, keeps the lowest PEP level as its source.

CREATE TABLE IF NOT EXISTS public.word_clean (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word varchar(100) NOT NULL,
    meaning varchar(200) NOT NULL,
    difficulty int2 DEFAULT 50 NOT NULL,
    frequency int2 DEFAULT 50 NOT NULL,
    sentence varchar(800) DEFAULT ''::character varying NULL,
    pep_difficulty int2 NULL,
    pep_difficulty_label varchar(200) NULL,
    source_difficulty int2 NULL,
    source_difficulty_label varchar(200) NULL
);

COMMENT ON TABLE public.word_clean IS '去重后的单词表，不包含词组';
COMMENT ON COLUMN public.word_clean.id IS 'id';
COMMENT ON COLUMN public.word_clean.word IS '英文单词';
COMMENT ON COLUMN public.word_clean.meaning IS '中文含义';
COMMENT ON COLUMN public.word_clean.difficulty IS '难度分';
COMMENT ON COLUMN public.word_clean.frequency IS '使用频率';
COMMENT ON COLUMN public.word_clean.sentence IS '例句';
COMMENT ON COLUMN public.word_clean.pep_difficulty IS '人教版教材难度等级，数字越小越基础';
COMMENT ON COLUMN public.word_clean.pep_difficulty_label IS '人教版教材难度标签';
COMMENT ON COLUMN public.word_clean.source_difficulty IS '统一来源难度等级，数字越小越基础，包含人教版、四六级、考研、专四专八、雅思托福、SAT、GRE 等';
COMMENT ON COLUMN public.word_clean.source_difficulty_label IS '统一来源难度标签';

ALTER TABLE public.word_clean
    ADD COLUMN IF NOT EXISTS pep_difficulty int2 NULL;

ALTER TABLE public.word_clean
    ADD COLUMN IF NOT EXISTS pep_difficulty_label varchar(200) NULL;

ALTER TABLE public.word_clean
    ADD COLUMN IF NOT EXISTS source_difficulty int2 NULL;

ALTER TABLE public.word_clean
    ADD COLUMN IF NOT EXISTS source_difficulty_label varchar(200) NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_word_clean_word_lower ON public.word_clean (lower(word));
CREATE UNIQUE INDEX IF NOT EXISTS uk_word_clean_word ON public.word_clean(word);
CREATE INDEX IF NOT EXISTS idx_word_clean_difficulty ON public.word_clean(difficulty);
CREATE INDEX IF NOT EXISTS idx_word_clean_frequency ON public.word_clean(frequency);
CREATE INDEX IF NOT EXISTS idx_word_clean_pep_difficulty ON public.word_clean(pep_difficulty);
CREATE INDEX IF NOT EXISTS idx_word_clean_source_difficulty ON public.word_clean(source_difficulty);

TRUNCATE TABLE public.word_clean RESTART IDENTITY;

WITH pep_levels(library_name, pep_difficulty) AS (
    VALUES
        ('PEPXiaoXue3_1', 1),
        ('PEPXiaoXue3_2', 2),
        ('PEPXiaoXue4_1', 3),
        ('PEPXiaoXue4_2', 4),
        ('PEPXiaoXue5_1', 5),
        ('PEPXiaoXue5_2', 6),
        ('PEPXiaoXue6_1', 7),
        ('PEPXiaoXue6_2', 8),
        ('PEPChuZhong7_1', 9),
        ('PEPChuZhong7_2', 10),
        ('PEPChuZhong8_1', 11),
        ('PEPChuZhong8_2', 12),
        ('PEPChuZhong9_1', 13),
        ('PEPGaoZhong_1', 14),
        ('PEPGaoZhong_2', 15),
        ('PEPGaoZhong_3', 16),
        ('PEPGaoZhong_4', 17),
        ('PEPGaoZhong_5', 18),
        ('PEPGaoZhong_6', 19),
        ('PEPGaoZhong_7', 20),
        ('PEPGaoZhong_8', 21),
        ('PEPGaoZhong_9', 22),
        ('PEPGaoZhong_10', 23),
        ('PEPGaoZhong_11', 24)
),
ranked AS (
    SELECT
        btrim(w.word) AS word,
        w.meaning,
        COALESCE(w.difficulty, 50) AS difficulty,
        COALESCE(w.frequency, 50) AS frequency,
        COALESCE(w.sentence, '') AS sentence,
        row_number() OVER (
            PARTITION BY lower(btrim(w.word))
            ORDER BY pl.pep_difficulty NULLS LAST, w.id
        ) AS row_number
    FROM public.word w
    LEFT JOIN public.word_library wl ON wl.id = w.library_id
    LEFT JOIN pep_levels pl ON pl.library_name = wl.library_name
    WHERE w.word IS NOT NULL
      AND btrim(w.word) <> ''
      AND btrim(w.word) !~ '\s'
)
INSERT INTO public.word_clean (word, meaning, difficulty, frequency, sentence)
SELECT
    ranked.word,
    ranked.meaning,
    ranked.difficulty,
    ranked.frequency,
    ranked.sentence
FROM ranked
WHERE ranked.row_number = 1
ORDER BY lower(ranked.word);

WITH pep_levels(library_name, pep_difficulty, pep_difficulty_label) AS (
    VALUES
        ('PEPXiaoXue3_1', 1, '小学英语3年级上册'),
        ('PEPXiaoXue3_2', 2, '小学英语3年级下册'),
        ('PEPXiaoXue4_1', 3, '小学英语4年级上册'),
        ('PEPXiaoXue4_2', 4, '小学英语4年级下册'),
        ('PEPXiaoXue5_1', 5, '小学英语5年级上册'),
        ('PEPXiaoXue5_2', 6, '小学英语5年级下册'),
        ('PEPXiaoXue6_1', 7, '小学英语6年级上册'),
        ('PEPXiaoXue6_2', 8, '小学英语6年级下册'),
        ('PEPChuZhong7_1', 9, '初中英语7年级上册'),
        ('PEPChuZhong7_2', 10, '初中英语7年级下册'),
        ('PEPChuZhong8_1', 11, '初中英语8年级上册'),
        ('PEPChuZhong8_2', 12, '初中英语8年级下册'),
        ('PEPChuZhong9_1', 13, '初中英语9年级上册'),
        ('PEPGaoZhong_1', 14, '高中英语上册'),
        ('PEPGaoZhong_2', 15, '高中英语下册'),
        ('PEPGaoZhong_3', 16, '高中英语第3册'),
        ('PEPGaoZhong_4', 17, '高中英语第4册'),
        ('PEPGaoZhong_5', 18, '高中英语第5册'),
        ('PEPGaoZhong_6', 19, '高中英语第6册'),
        ('PEPGaoZhong_7', 20, '高中英语第7册'),
        ('PEPGaoZhong_8', 21, '高中英语第8册'),
        ('PEPGaoZhong_9', 22, '高中英语第9册'),
        ('PEPGaoZhong_10', 23, '高中英语第10册'),
        ('PEPGaoZhong_11', 24, '高中英语第11册')
),
word_pep_level AS (
    SELECT
        lower(btrim(w.word)) AS word_key,
        min(pl.pep_difficulty) AS pep_difficulty
    FROM public.word w
    JOIN public.word_library wl ON wl.id = w.library_id
    JOIN pep_levels pl ON pl.library_name = wl.library_name
    WHERE w.word IS NOT NULL
      AND btrim(w.word) <> ''
      AND btrim(w.word) !~ '\s'
    GROUP BY lower(btrim(w.word))
),
word_pep_label AS (
    SELECT
        wpl.word_key,
        wpl.pep_difficulty,
        pl.pep_difficulty_label
    FROM word_pep_level wpl
    JOIN pep_levels pl ON pl.pep_difficulty = wpl.pep_difficulty
)
UPDATE public.word_clean wc
SET pep_difficulty = wpl.pep_difficulty,
    pep_difficulty_label = wpl.pep_difficulty_label
FROM word_pep_label wpl
WHERE lower(btrim(wc.word)) = wpl.word_key;

WITH source_levels(library_name, source_difficulty, source_difficulty_label) AS (
    VALUES
        ('PEPXiaoXue3_1', 1, '小学英语3年级上册'),
        ('PEPXiaoXue3_2', 2, '小学英语3年级下册'),
        ('PEPXiaoXue4_1', 3, '小学英语4年级上册'),
        ('PEPXiaoXue4_2', 4, '小学英语4年级下册'),
        ('PEPXiaoXue5_1', 5, '小学英语5年级上册'),
        ('PEPXiaoXue5_2', 6, '小学英语5年级下册'),
        ('PEPXiaoXue6_1', 7, '小学英语6年级上册'),
        ('PEPXiaoXue6_2', 8, '小学英语6年级下册'),
        ('PEPChuZhong7_1', 9, '初中英语7年级上册'),
        ('PEPChuZhong7_2', 10, '初中英语7年级下册'),
        ('PEPChuZhong8_1', 11, '初中英语8年级上册'),
        ('PEPChuZhong8_2', 12, '初中英语8年级下册'),
        ('PEPChuZhong9_1', 13, '初中英语9年级上册'),
        ('PEPGaoZhong_1', 14, '高中英语上册'),
        ('PEPGaoZhong_2', 15, '高中英语下册'),
        ('PEPGaoZhong_3', 16, '高中英语第3册'),
        ('PEPGaoZhong_4', 17, '高中英语第4册'),
        ('PEPGaoZhong_5', 18, '高中英语第5册'),
        ('PEPGaoZhong_6', 19, '高中英语第6册'),
        ('PEPGaoZhong_7', 20, '高中英语第7册'),
        ('PEPGaoZhong_8', 21, '高中英语第8册'),
        ('PEPGaoZhong_9', 22, '高中英语第9册'),
        ('PEPGaoZhong_10', 23, '高中英语第10册'),
        ('PEPGaoZhong_11', 24, '高中英语第11册'),
        ('CET4_1', 25, '大学英语四级'),
        ('CET4_2', 25, '大学英语四级'),
        ('CET4_3', 25, '大学英语四级'),
        ('CET4luan_1', 25, '大学英语四级'),
        ('CET4luan_2', 25, '大学英语四级'),
        ('KaoYan_1', 26, '考研英语'),
        ('KaoYan_2', 26, '考研英语'),
        ('KaoYan_3', 26, '考研英语'),
        ('KaoYanluan_1', 26, '考研英语'),
        ('BEC_2', 27, '商务英语 BEC'),
        ('BEC_3', 27, '商务英语 BEC'),
        ('CET6_1', 28, '大学英语六级'),
        ('CET6_2', 28, '大学英语六级'),
        ('CET6_3', 28, '大学英语六级'),
        ('CET6luan_1', 28, '大学英语六级'),
        ('IELTS_2', 29, '雅思'),
        ('IELTS_3', 29, '雅思'),
        ('IELTSluan_2', 29, '雅思'),
        ('Level4_1', 30, '英语专业四级'),
        ('Level4_2', 30, '英语专业四级'),
        ('Level4luan_1', 30, '英语专业四级'),
        ('Level4luan_2', 30, '英语专业四级'),
        ('Level8_1', 31, '英语专业八级'),
        ('Level8_2', 31, '英语专业八级'),
        ('Level8luan_2', 31, '英语专业八级'),
        ('TOEFL_2', 32, '托福'),
        ('TOEFL_3', 32, '托福'),
        ('GMAT_2', 33, 'GMAT'),
        ('GMAT_3', 33, 'GMAT'),
        ('GMATluan_2', 33, 'GMAT'),
        ('SAT_2', 34, 'SAT'),
        ('SAT_3', 34, 'SAT'),
        ('GRE_2', 35, 'GRE'),
        ('GRE_3', 35, 'GRE')
),
word_source_level AS (
    SELECT
        lower(btrim(w.word)) AS word_key,
        min(sl.source_difficulty) AS source_difficulty
    FROM public.word w
    JOIN public.word_library wl ON wl.id = w.library_id
    JOIN source_levels sl ON sl.library_name = wl.library_name
    WHERE w.word IS NOT NULL
      AND btrim(w.word) <> ''
      AND btrim(w.word) !~ '\s'
    GROUP BY lower(btrim(w.word))
),
word_source_label AS (
    SELECT
        wsl.word_key,
        wsl.source_difficulty,
        sl.source_difficulty_label
    FROM word_source_level wsl
    JOIN source_levels sl ON sl.source_difficulty = wsl.source_difficulty
    GROUP BY wsl.word_key, wsl.source_difficulty, sl.source_difficulty_label
)
UPDATE public.word_clean wc
SET source_difficulty = wsl.source_difficulty,
    source_difficulty_label = wsl.source_difficulty_label
FROM word_source_label wsl
WHERE lower(btrim(wc.word)) = wsl.word_key;

UPDATE public.word_clean
SET source_difficulty = 36,
    source_difficulty_label = '其他词库'
WHERE source_difficulty IS NULL;
